"""empty message

Revision ID: 25dd466dc1d3
Revises: 86b823c1980c
Create Date: 2023-12-15 18:30:54.757042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dd466dc1d3'
down_revision = '86b823c1980c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urunler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adi', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('kodu', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fiyati', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('aciklamasi', sa.String(), nullable=False))
        batch_op.drop_column('urun_kodu')
        batch_op.drop_column('urun_fiyati')
        batch_op.drop_column('urun_aciklamasi')
        batch_op.drop_column('urun_adi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urunler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urun_adi', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('urun_aciklamasi', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('urun_fiyati', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('urun_kodu', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('aciklamasi')
        batch_op.drop_column('fiyati')
        batch_op.drop_column('kodu')
        batch_op.drop_column('adi')

    # ### end Alembic commands ###
