"""empty message

Revision ID: 86b823c1980c
Revises: 
Create Date: 2023-12-13 21:42:05.650163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b823c1980c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magaza',
    sa.Column('magaza_adi', sa.String(), nullable=False),
    sa.Column('magaza_adresi', sa.String(), nullable=False),
    sa.Column('magaza_tel', sa.String(), nullable=False),
    sa.Column('magaza_yetkilikisi', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteri',
    sa.Column('musteri_adi', sa.String(), nullable=False),
    sa.Column('musteri_soyadi', sa.String(), nullable=False),
    sa.Column('musteri_cinsiyeti', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_kategorisi',
    sa.Column('kategori_adi', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urunler',
    sa.Column('urun_adi', sa.String(), nullable=False),
    sa.Column('urun_kodu', sa.String(), nullable=False),
    sa.Column('urun_fiyati', sa.Float(), nullable=False),
    sa.Column('urun_aciklamasi', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis',
    sa.Column('urunler_id', sa.Integer(), nullable=False),
    sa.Column('siparis_tarihi', sa.Date(), nullable=False),
    sa.Column('firma', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.ForeignKeyConstraint(['urunler_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_ozellikleri',
    sa.Column('urunler_id', sa.Integer(), nullable=False),
    sa.Column('urun_ozelligi', sa.String(), nullable=False),
    sa.Column('urun_degeri', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['urunler_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis_urunu',
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('urunler_id', sa.Integer(), nullable=False),
    sa.Column('adeti', sa.Integer(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparis.id'], ),
    sa.ForeignKeyConstraint(['urunler_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_yorumu',
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('urunler_id', sa.Integer(), nullable=False),
    sa.Column('urun_yorumu', sa.String(), nullable=False),
    sa.Column('urun_puani', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparis.id'], ),
    sa.ForeignKeyConstraint(['urunler_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urun_yorumu')
    op.drop_table('siparis_urunu')
    op.drop_table('urun_ozellikleri')
    op.drop_table('siparis')
    op.drop_table('urunler')
    op.drop_table('urun_kategorisi')
    op.drop_table('musteri')
    op.drop_table('magaza')
    # ### end Alembic commands ###
